import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'specs';OUT.mkdir(exist_ok=True)
BLUE='#2457D6';TEAL='#007F78';GOLD='#B47716';INK='#162B4D'
types=['Domestic day','Domestic overnight','International'];colors=[GOLD,TEAL,BLUE]
config={'font':'IBM Plex Sans','view':{'stroke':None},'axis':{'labelFontSize':12,'titleFontSize':12,'titleFontWeight':'normal','gridColor':'#DFE6EE','domain':False,'tickColor':'#B3C2D3','labelColor':INK,'titleColor':INK,'titlePadding':12,'labelLimit':150},'legend':{'labelFontSize':12,'titleFontSize':12,'orient':'bottom','title':None},'title':{'fontSize':14,'anchor':'start','color':INK}}
def save(n,s,vega=False):
 s={'$schema':'https://vega.github.io/schema/vega/v5.json' if vega else 'https://vega.github.io/schema/vega-lite/v5.json',**s}
 if not vega:s={'width':'container','height':300,'config':config,**s}
 (OUT/(n+'.json')).write_text(json.dumps(s,indent=2,ensure_ascii=False),encoding='utf-8')
def data(n,geo=False):return {'url':'data/'+n+'.json',**({'format':{'type':'json','property':'features'}} if geo else {})}
def f(field,t='Q',**kw):return {'field':field,'type':{'Q':'quantitative','N':'nominal','O':'ordinal','T':'temporal'}[t],**kw}
def typcol():return f('traveller','N',scale={'domain':types,'range':colors})
def tip(field,title=None,fmt=None,t='Q'):return f(field,t,**({'title':title} if title else {}),**({'format':fmt} if fmt else {}))
panels=[]
for metric in ['Visitor trips','Spending in Australia']:
 panels.append({'width':180,'height':180,'title':metric,'data':data('waffle'),'transform':[{'filter':f'datum.metric === "{metric}"'}],'mark':{'type':'rect','cornerRadius':2,'stroke':'white','strokeWidth':2},'encoding':{'x':f('x','O',axis=None),'y':f('y','O',axis=None),'color':typcol(),'tooltip':[tip('traveller','Traveller',t='N'),tip('share','Exact share','.1%')]}})
save('01-waffle',{'hconcat':panels,'spacing':28,'resolve':{'scale':{'color':'shared'}},'height':180})
save('02-spend-per-trip',{'data':data('national'),'transform':[{'filter':'datum.year == 2025'}],'height':220,'layer':[{'mark':{'type':'bar','cornerRadiusEnd':3},'encoding':{'x':f('spend_per_trip',title='AUD spent in Australia per visitor trip',axis={'format':'$,.0f'},scale={'domain':[0,3800]}),'y':f('traveller','N',sort=['International','Domestic overnight','Domestic day'],title=None),'color':{**typcol(),'legend':None},'tooltip':[tip('traveller',t='N'),tip('spend_per_trip','AUD per trip','$,.0f')]}},{'mark':{'type':'text','align':'left','dx':7,'fontSize':13,'color':INK},'encoding':{'x':f('spend_per_trip'),'y':f('traveller','N',sort=['International','Domestic overnight','Domestic day']),'text':f('spend_per_trip',format='$,.0f')}}]})
save('03-sankey',{'height':300,'layer':[{'data':data('flows'),'mark':{'type':'area','opacity':.8},'encoding':{'x':f('x',axis=None,scale={'domain':[-.03,1.03]}),'y':f('y',axis=None,scale={'domain':[21,0]}),'y2':{'field':'y2'},'detail':f('link','N'),'color':{**typcol(),'legend':None},'tooltip':[tip('link','Flow',t='N'),tip('value','AUD','$,.0f')]}},{'data':data('flow-nodes'),'mark':{'type':'rule','strokeWidth':7,'color':INK},'encoding':{'x':f('x'),'y':f('y'),'y2':{'field':'y2'}}},{'data':data('flow-nodes'),'transform':[{'filter':'datum.x == 1'},{'calculate':'(datum.y + datum.y2)/2','as':'mid'}],'mark':{'type':'text','align':'right','dx':-10,'color':'white','stroke':INK,'strokeWidth':.2,'fontWeight':'bold','fontSize':12},'encoding':{'x':f('x'),'y':f('mid'),'text':f('label','N')}}]})
projection={'type':'conicEqualArea','parallels':[-18,-36],'rotate':[-134,0,0],'center':[0,-28]}
base={'data':data('australia',True),'mark':{'type':'geoshape','stroke':'white','strokeWidth':1},'encoding':{'tooltip':[tip('properties.state','State',t='N'),tip('properties.spend_per_resident','AUD per resident','$,.0f'),tip('properties.spend','Spending (AUD)','$,.0f'),tip('properties.population','Residents',',.0f')]}}
save('04-choropleth',{'height':380,'projection':projection,'layer':[{**base,'encoding':{**base['encoding'],'color':f('properties.spend_per_resident',scale={'domain':[0,1600],'range':['#EDF4FA','#193D91']},legend={'title':'AUD per resident','format':'$,.0f','gradientLength':220})}},{'data':data('states'),'mark':{'type':'text','fontWeight':'bold','fontSize':12,'color':INK,'stroke':'white','strokeWidth':2},'encoding':{'longitude':f('label_lon'),'latitude':f('label_lat'),'text':f('code','N')}},{'data':{'values':[{'longitude':148.983,'latitude':-35.4618,'lon2':153,'lat2':-36.7}]},'mark':{'type':'rule','color':INK},'encoding':{'longitude':f('longitude'),'latitude':f('latitude'),'longitude2':{'field':'lon2'},'latitude2':{'field':'lat2'}}}]})
save('05-symbol-map',{'height':380,'projection':projection,'layer':[{'data':data('australia',True),'mark':{'type':'geoshape','fill':'#EDF1F5','stroke':'white'}},{'data':data('states'),'mark':{'type':'circle','fill':BLUE,'fillOpacity':.55,'stroke':BLUE,'strokeWidth':1.5},'encoding':{'longitude':f('longitude'),'latitude':f('latitude'),'size':f('visitors',scale={'domain':[0,7500000],'range':[0,4400]},legend={'title':'State visits','format':'.1s','values':[1000000,4000000,7000000]}),'tooltip':[tip('state',t='N'),tip('visitors','State visits',',.0f')]}},{'data':data('states'),'mark':{'type':'text','dy':-3,'fontWeight':'bold','color':INK,'stroke':'white','strokeWidth':2},'encoding':{'longitude':f('label_lon'),'latitude':f('label_lat'),'text':f('code','N')}}]})
save('06-treemap',{'width':1000,'height':380,'padding':0,'autosize':'none','data':[{'name':'tree','url':'data/regions.json','transform':[{'type':'stratify','key':'id','parentKey':'parent'},{'type':'treemap','field':'value','sort':{'field':'value','order':'descending'},'method':'squarify','size':[{'signal':'width'},{'signal':'height'}],'paddingInner':3,'paddingOuter':3,'paddingTop':22}]},{'name':'leaves','source':'tree','transform':[{'type':'filter','expr':'!datum.children'}]},{'name':'parents','source':'tree','transform':[{'type':'filter','expr':'datum.depth == 1'}]}],'scales':[{'name':'color','type':'ordinal','domain':['NSW','VIC','QLD','WA','SA','ACT','NT','TAS'],'range':['#2457D6','#007F78','#426BA0','#4F6D58','#A06C20','#805C89','#377E8C','#6A779C']}],'marks':[{'type':'rect','from':{'data':'leaves'},'encode':{'enter':{'x':{'field':'x0'},'y':{'field':'y0'},'x2':{'field':'x1'},'y2':{'field':'y1'},'fill':{'scale':'color','field':'parent'},'tooltip':{'signal':"{'Region':datum.name, 'Spending (AUD)':format(datum.value,'$,.0f')}"}},'update':{'fillOpacity':{'value':1}},'hover':{'fillOpacity':{'value':.7}}}},{'type':'text','from':{'data':'leaves'},'encode':{'update':{'x':{'signal':'datum.x0+7'},'y':{'signal':'datum.y0+16'},'text':{'field':'name'},'limit':{'signal':'max(0, datum.x1-datum.x0-14)'},'opacity':{'signal':'datum.y1-datum.y0>27 && datum.x1-datum.x0>55 ? 1:0'},'font':{'value':'IBM Plex Sans'},'fontSize':{'value':12},'fill':{'value':'white'}}}},{'type':'text','from':{'data':'leaves'},'encode':{'update':{'x':{'signal':'datum.x0+7'},'y':{'signal':'datum.y0+33'},'text':{'signal':"format(datum.value/1e9,'$.2f')+'b'"},'opacity':{'signal':'datum.y1-datum.y0>45 && datum.x1-datum.x0>75 ? 1:0'},'font':{'value':'IBM Plex Sans'},'fontSize':{'value':12},'fill':{'value':'white'}}}},{'type':'text','from':{'data':'parents'},'encode':{'update':{'x':{'signal':'datum.x0+5'},'y':{'signal':'datum.y0+16'},'text':{'field':'name'},'font':{'value':'IBM Plex Sans'},'fontWeight':{'value':'bold'},'fill':{'value':INK}}}}]},True)
save('07-flow-map',{'height':440,'projection':{'type':'equalEarth','rotate':[-150,0,0]},'layer':[{'data':data('world',True),'mark':{'type':'geoshape','fill':'#E8EFF5','stroke':'white','strokeWidth':.5}},{'data':data('routes',True),'mark':{'type':'geoshape','filled':False,'strokeOpacity':.6},'encoding':{'strokeWidth':f('properties.visitors',scale={'domain':[0,165000],'range':[0,12]},legend={'title':'Visitor trips','values':[50000,100000,150000],'format':'.0s'}),'stroke':{'condition':{'test':"datum.properties.country == 'Malaysia'",'value':TEAL},'value':BLUE},'tooltip':[tip('properties.country','Origin',t='N'),tip('properties.visitors','Visitor trips',',.0f')]}},{'data':data('origins'),'mark':{'type':'circle','size':50,'color':INK},'encoding':{'longitude':f('longitude'),'latitude':f('latitude'),'tooltip':[tip('country','Origin',t='N'),tip('visitors','Visitor trips',',.0f')]}},{'data':{'values':[{'longitude':149.129,'latitude':-35.283,'label':'Australia'},{'longitude':101.689,'latitude':3.14,'label':'Malaysia'}]},'mark':{'type':'text','dy':18,'fontWeight':'bold','color':INK},'encoding':{'longitude':f('longitude'),'latitude':f('latitude'),'text':f('label','N')}}]})
save('08-market-scatter',{'data':data('markets'),'params':[{'name':'year','value':2025,'bind':{'input':'select','options':[2024,2025],'name':'Year: '}},{'name':'focus','value':'All markets','bind':{'input':'select','options':['All markets','Malaysia','China','New Zealand','Singapore','USA','UK'],'name':'Highlight: '}}],'transform':[{'filter':'datum.year == year'}],'height':360,'layer':[{'mark':{'type':'circle','size':110,'stroke':'white','strokeWidth':1},'encoding':{'x':f('visitors',title='Visitor trips',axis={'format':'~s'},scale={'domain':[0,185000]}),'y':f('spend',title='Spending in Australia (AUD)',axis={'format':'$~s'},scale={'domain':[0,400000000]}),'color':{'condition':{'test':"datum.country == 'Malaysia'",'value':TEAL},'value':BLUE},'opacity':{'condition':{'test':"focus == 'All markets' || datum.country == focus",'value':.85},'value':.12},'tooltip':[tip('country','Origin',t='N'),tip('visitors','Visitor trips',',.0f'),tip('spend','Spending (AUD)','$,.0f')]}},{'transform':[{'filter':"datum.country == 'Malaysia' || datum.visitors > 70000 || datum.country == focus"}],'mark':{'type':'text','dx':6,'dy':-9,'align':'left','fontSize':11,'color':INK},'encoding':{'x':f('visitors'),'y':f('spend'),'text':f('country','N')}}]})
save('09-change-heatmap',{'data':data('changes'),'height':420,'encoding':{'x':f('metric','O',sort=['Visitors','Nights','Spend'],title=None,axis={'orient':'top','labelAngle':0}),'y':f('country','N',sort={'field':'change','op':'mean','order':'descending'},title=None)},'layer':[{'mark':{'type':'rect','stroke':'white','strokeWidth':2},'encoding':{'color':f('change',scale={'domain':[-.65,0,.65],'range':['#915114','#FFFFFF','#2457D6'],'clamp':True},legend={'title':'Change, 2024 → 2025','format':'+.0%','gradientLength':190}),'tooltip':[tip('country',t='N'),tip('metric',t='N'),tip('change','Change','+.1%'),tip('before','2024',',.0f'),tip('after','2025',',.0f')]}},{'mark':{'type':'text','fontSize':12},'encoding':{'text':f('change',format='+.0%'),'color':{'condition':{'test':'abs(datum.change) > 0.35','value':'white'},'value':INK}}}]})
save('10-waterfall',{'data':data('waterfall'),'height':300,'encoding':{'x':f('label','O',sort={'field':'order','order':'ascending'},title=None,axis={'labelAngle':-25,'labelLimit':160})},'layer':[{'mark':{'type':'bar','size':46},'encoding':{'y':f('start',title='Spending in Australia (AUD billions)',scale={'domain':[0,2.95]}),'y2':{'field':'end'},'color':f('kind','N',scale={'domain':['Total','Increase','Decrease'],'range':[INK,BLUE,GOLD]},legend=None),'tooltip':[tip('label','Contribution',t='N'),tip('value','AUD billions','+.3f')]}},{'transform':[{'calculate':'max(datum.start,datum.end)','as':'top'},{'calculate':"datum.kind == 'Total' ? format(datum.value,'$.2f')+'b' : format(datum.value*1000,'+,.0f')+'m'",'as':'display'}],'mark':{'type':'text','dy':-8,'fontSize':12,'color':INK},'encoding':{'y':f('top'),'text':f('display','N')}}]})
save('11-activity-slope',{'data':data('activities'),'height':360,'encoding':{'x':f('year','O',title=None,axis={'labelAngle':0},scale={'padding':.25}),'y':f('share',title='Share of international event attendees',axis={'format':'.0%'},scale={'domain':[.1,1]})},'layer':[{'mark':{'type':'line','point':{'filled':True,'size':55},'strokeWidth':2},'encoding':{'detail':f('activity','N'),'color':f('activity','N',scale={'range':[BLUE,TEAL,GOLD,'#805C89','#576D84']},legend={'labelLimit':200,'columns':1}),'tooltip':[tip('activity',t='N'),tip('year',t='O'),tip('share','Participation','.1%')]}},{'mark':{'type':'text','dy':-11,'fontSize':11,'color':INK},'encoding':{'text':f('share',format='.1%'),'detail':f('activity','N')}}]})
save('12-per-night',{'data':data('per-night'),'height':240,'encoding':{'y':f('year','O',title=None),'x':f('other',title='Spending in Australia per visitor night (AUD)',scale={'domain':[0,180]},axis={'format':'$,.0f'})},'layer':[{'mark':{'type':'rule','strokeWidth':4,'color':'#B3C2D3'},'encoding':{'x2':{'field':'business'}}},{'mark':{'type':'circle','size':150,'color':'#576D84','opacity':1},'encoding':{'tooltip':[tip('other','Other international visitors','$,.0f')]}},{'mark':{'type':'circle','size':150,'color':BLUE,'opacity':1},'encoding':{'x':f('business'),'tooltip':[tip('business','Business-event visitors','$,.0f')]}},{'mark':{'type':'text','dy':-18,'color':INK},'encoding':{'text':f('other',format='$,.0f')}},{'mark':{'type':'text','dy':-18,'color':INK},'encoding':{'x':f('business'),'text':f('business',format='$,.0f')}}]})
# Refinements after inspecting the rendered figures.
for path in OUT.glob('*.json'):
 s=json.loads(path.read_text(encoding='utf-8'))
 if path.name.startswith('01-'):
  for panel in s['hconcat']:panel['encoding']['color']['legend']=None
 if path.name.startswith(('02-','08-','12-')):
  s['config']['axis']['tickCount']=5
 if path.name.startswith(('04-','05-')):
  label=s['layer'][1 if path.name.startswith('04-') else 2]
  label['mark'].pop('stroke',None);label['mark'].pop('strokeWidth',None)
  label['mark']['fontSize']=12
  if path.name.startswith('04-'):label['encoding']['color']={'condition':{'test':"datum.code == 'NT'",'value':'white'},'value':INK}
 if path.name.startswith('07-'):
  s['layer'][1]['encoding']['strokeWidth']['legend']['symbolType']='stroke'
  s['layer'][1]['encoding']['strokeWidth']['legend']['format']='~s'
 if path.name.startswith('08-'):
  s['layer'][1]['mark']['align']={'expr':"datum.country == 'New Zealand' ? 'right' : 'left'"}
  s['layer'][1]['mark']['dx']={'expr':"datum.country == 'New Zealand' ? -6 : 6"}
 if path.name.startswith('09-'):
  s['layer'][0]['encoding']['color']['scale']['interpolate']='rgb'
  s['layer'][1]['encoding']['color']['condition']['test']='abs(datum.change) > 0.48'
 if path.name.startswith('11-'):
  s['transform']=[{'filter':"datum.activity != 'Go shopping'"}]
 if path.name.startswith('03-'):
  s['layer'].append({'data':data('flow-nodes'),'transform':[{'filter':'datum.x == 0'},{'calculate':"(datum.y + datum.y2)/2 - (datum.label == 'International' ? 0.6 : 0)",'as':'mid'}],'mark':{'type':'text','align':'left','dx':10,'color':'white','fontSize':11,'fontWeight':'bold'},'encoding':{'x':f('x'),'y':f('mid'),'text':f('label','N')}})
 path.write_text(json.dumps(s,indent=2,ensure_ascii=False),encoding='utf-8')
print('Wrote',len(list(OUT.glob('*.json'))),'readable chart specifications')
